name: aigc_det_baseline
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pandas
  - numpy
  - pillow
  - tqdm
  - scikit-learn
  - matplotlib
  - pyyaml
  - pip
  - pip:
      - kaggle
      - open_clip_torch
      - datasets>=3.0,<5
      - pyarrow>=15
      - huggingface_hub>=0.25
