experiment_name: cifake_full_resnet50
model_type: resnet
model_name: resnet50
dataset: CIFAKE
train_csv: outputs/splits/cifake_full_train.csv
val_csv: outputs/splits/cifake_full_test.csv
test_csv: outputs/splits/cifake_full_test.csv
image_size: 224
batch_size: 16
epochs: 3
pretrained: true
freeze_backbone: false
mixed_precision: true
learning_rate: 0.0001
seed: 42
num_workers: 2
